######## 文件存储服务 ########
storage_enabled: true
storage_supplier: "ali_oss"
# 阿里云OSS
ali_oss:
  endpoint: ""
  access_key_id: ""
  access_key_secret: ""
  bucket: ""
  directory: "draw_hub/"

######## 图片生成服务 ########
# 极客智坊 https://geekai.dev/
geek:
  low_price_token: ""
  balance_token: ""
  high_available_token: ""
# V_API https://api.v3.cm/
v_api:
  token: ""
# 兔子API https://api.tu-zi.com/
tuzi_api:
  default_channel_token: ""
  openai_channel_token: ""

# 请求顺序
# 1. 先请求极客智坊的低价接口
# 2. 如果极客智坊的低价接口失败，再访问均衡接口
# ...
request_order:
# 低速接口请求顺序(调用gpt-4o-image、gpt-4o-image-vip)
  low_speed:
    - tuzi_api.default_channel_token
    - geek.low_price_token
    - tuzi_api.default_channel_token.vip
    - v_api.token
    - v_api.toke.vip
  # 高速接口请求顺序(gpt-image-1)
  high_speed:
    - geek.low_price_token
    - geek.balance_token
    - geek.high_available_token
    - v_api.token
    - tuzi_api.openai_channel_token