######## 文件存储服务 ########
storage_enabled: true
storage_supplier: "ali_oss"
url_expires: "168h"
# 阿里云OSS
ali_oss:
  endpoint: "https://oss-ap-southeast-1.aliyuncs.com"
  access_key_id: ""
  access_key_secret: ""
  bucket: ""
  region: "ap-southeast-1"
  directory: "draw_hub/"
mysql:
  host: ""
  port: 3306
  username: ""
  password: ""
  database: "draw_hub"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100

######## 图片生成服务 ########
# 极客智坊 https://geekai.dev/
# V_API https://api.v3.cm/
# 兔子API https://api.tu-zi.com/

# 请求顺序
# 1. 先请求极客智坊的低价接口
# 2. 如果极客智坊的低价接口失败，再访问均衡接口
# ...
request_order:
  # 低速接口请求顺序(调用gpt-4o-image、gpt-4o-image-vip)
  slow_speed:
    -
      supplier: "tuzi"
      token: "sk-"
      desc: "default"
      model: "gpt-4o-image"
    -
      supplier: "geek"
      token: "sk-"
      desc: "low_price"
      model: "gpt-4o-image"
    -
      supplier: "tuzi"
      token: "sk-"
      desc: "default"
      model: "gpt-4o-image-vip"
    -
      supplier: "v3"
      token: "sk-"
      desc: "default"
      model: "gpt-4o-image"
    -
      supplier: "v3"
      token: "sk-"
      desc: "default"
      model: "gpt-4o-image-vip"
  # 高速接口请求顺序(gpt-image-1)
  fast_speed:
    -
      supplier: "geek"
      token: "sk-"
      desc: "low_price"
      model: "gpt-image-1"
    -
      supplier: "geek"
      token: "sk-"
      desc: "balance"
      model: "gpt-image-1"
    -
      supplier: "geek"
      token: "sk-"
      desc: "high_available"
      model: "gpt-image-1"
    -
      supplier: "v3"
      token: "sk-"
      desc: "default"
      model: "gpt-image-1"
    -
      supplier: "tuzi"
      token: "sk-"
      desc: "openai_channel"
      model: "gpt-image-1"
  # grok deepsearch
  deepsearch:
    - supplier: "geek"
      token: "sk-"
      desc: "low_price"
      model: "grok-3-deepsearch"
    - supplier: "tuzi"
      token: "sk-"
      desc: "default"
      model: "grok-3-deepsearch"