######## 日志配置 ########
# 日志级别: trace, debug, info, warn, error, fatal, panic
# 生产环境建议使用 info 或以上级别
log_level: "debug"  # 开发环境使用debug，生产环境建议使用info
log_file: "draw_hub.logs"
log_max_size: 10    # 单个日志文件最大大小（MB）
log_max_backups: 5  # 保留旧日志文件的最大数量
log_max_age: 30     # 日志文件保留的最大天数

######## 文件存储服务 ########
# 存储服务器域名
local_storage_domain: "https://draw-hub.example.com"
# 本地存储目录
local_storage_directory: "storage/"
# 云存储服务
cloud_storage_enabled: false
cloud_storage_supplier: "ali_oss"
url_expires: "168h"
# 阿里云OSS
ali_oss:
  endpoint: "https://oss-ap-southeast-1.aliyuncs.com"
  access_key_id: ""
  access_key_secret: ""
  bucket: ""
  region: "ap-southeast-1"
  directory: "draw_hub/"
mysql:
  host: ""
  port: 3306
  username: ""
  password: ""
  database: "draw_hub"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100

######## 图片生成服务 ########
# 极客智坊 https://geekai.dev/chat?invite_code=naHMII
# V3_API https://api.v3.cm/register?aff=ROjp
# 兔子API https://api.tu-zi.com/register?aff=ROfC

token:
  -
    supplier: "tuzi"
    token: ""
    desc: "default"
  -
    supplier: "tuzi"
    token: ""
    desc: "openai_channel"
  -
    supplier: "tuzi"
    token: ""
    desc: "multichannel"
  -
    supplier: "tuzi"
    token: ""
    desc: "mj"
  -
    supplier: "geek"
    token: ""
    desc: "low_price"
  -
    supplier: "geek"
    token: ""
    desc: "balance"
  -
    supplier: "geek"
    token: ""
    desc: "high_available"
  -
    supplier: "v3"
    token: ""
    desc: "default"

# 请求顺序
request_order:
  gpt-4o-image:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "gpt-4o-image"
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "gpt-4o-image"
    -
      -
        supplier: "v3"
        desc: "default"
        model: "gpt-4o-image"
  gpt-4o-image-vip:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "gpt-4o-image-vip"
    -
      -
        supplier: "v3"
        desc: "default"
        model: "gpt-4o-image-vip"
  gpt-image-1:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "gpt-image-1"
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "gpt-image-1"
    -
      -
        supplier: "geek"
        desc: "balance"
        model: "gpt-image-1"
    -
      -
        supplier: "geek"
        desc: "high_available"
        model: "gpt-image-1"
    -
      -
        supplier: "v3"
        desc: "default"
        model: "gpt-image-1"
    -
      -
        supplier: "tuzi"
        desc: "openai_channel"
        model: "gpt-image-1"
  deepsearch:
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "grok-3-deepsearch"
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "grok-3-deepsearch"
  gemini-2.5-flash-image:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "gemini-2.5-flash-image"
      -
        supplier: "tuzi"
        desc: "multichannel"
        model: "gemini-2.5-flash-image"
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "gemini-2.5-flash-image"
  gemini-2.5-flash-image-hd:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "gemini-2.5-flash-image-hd"
      -
        supplier: "tuzi"
        desc: "multichannel"
        model: "gemini-2.5-flash-image-hd"
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "gemini-nano-banana-hd"
  jimeng_t2i_v40:
    -
      -
        supplier: "tuzi"
        desc: "default"
        model: "doubao-seedream-4-0-250828"
      -
        supplier: "tuzi"
        desc: "multichannel"
        model: "doubao-seedream-4-0-250828"
    -
      -
        supplier: "geek"
        desc: "low_price"
        model: "doubao-seedream-4.0"
  midjourney:
    -
      -
        supplier: "tuzi"
        desc: "mj"
        model: "midjourney"
    -
      - supplier: "geek"
        desc: "low_price"
        model: "midjourney"
    -
      - supplier: "v3"
        desc: "default"
        model: "midjourney"